[versions]
# libraries
spring-boot = "3.5.8"
cosid = "3.0.0"
guava = "33.5.0-jre"
kotlin-logging = "7.0.13"
springdoc = "2.8.14"
# testing
junit = "5.14.1"
fluent-assert = "0.2.6"
mockk = "1.14.7"
# plugins
detekt = "1.23.8"
dokka = "2.1.0"
kotlin = "2.2.21"
publish-plugin = "2.0.0"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
cosid-bom = { module = "me.ahoo.cosid:cosid-bom", version.ref = "cosid" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
springdoc-openapi-starter-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
fluent-assert-bom = { module = "me.ahoo.test:fluent-assert-bom", version.ref = "fluent-assert" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }

